my_list = [1,2,3]
print(my_list)
my_list.append(4)
# append object to the end of the list
my_list.append(9)
print(my_list)
my_list.extend([5,6,7,"Nirmal","singh"])
my_list.insert(0,"Start")
print(my_list)
# remove()
my_list.remove("singh")
print(my_list)
print ("-----------------")
my_copy_list= my_list.copy()
print (my_list)
print(my_copy_list)

my_list.clear()
print(my_list)
print(my_copy_list)

print("^^^^^^^^^^^^^^^^")
my_copy_list.remove("Nirmal")
print(my_copy_list)
#my_copy_list.remove("start")
#print(my_copy_list)
my_copy_list.sort()
print(my_copy_list)
my_copy_list.reverse()
print(my_copy_list)